# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wikimedia Design Blog
description: Make sharing of knowledge easy and joyful, for everyone.
baseurl: "/blog/"
url: "https://design.wikimedia.org"
twitter_username: WikimediaDesign
github_username: wikimedia

# Build settings
theme: minima
timezone: UTC
paginate: 5
paginate_path: "/:num/"
# This default applies to `jekyll serve` and other commands during local development.
# For the committed production output, pass `-d _site` to `jekyll build`.
#
# This way, you can't accidentally commit the output generated by "serve",
# which break the base url used in links to images inside CSS or RSS feeds.
destination: _dev/

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
